### ISSUE TITLE
Marketplace Decay

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#100]
Thinking on the marketplace item production. Couple possible improvements :

- [ ] Can we use a decay function to the marketplace? Possibly even reset the entire marketplace on market refresh (bar the current items with bids)

- [x]  Can we add in a minimum bid for rarer items? Tiered items cost more to bid on. Possibly floor of 3 gold and goes up by one per tier.

**Comment by ponderingdemocritus** [comment]
I think the tiered approach is good @loothero wdyt?

**Comment by loothero** [comment]
Having the higher tiers items have a higher minimum bid is an excellent solution as it solves the "market creeper" problem in a very simple way.

Lets make the increase more significant though since the difference between the tiers is significant.

T5: 3 Gold
T4: 6 Gold
T3: 9 Gold
T2: 12 Gold
T1: 15 Gold

This ensures that the market stalkers still have to pay a hefty premium for all T1 gear. As part of this, we'll bump Charisma discount from 1 to 3 and have it apply to potions to (https://github.com/BibliothecaDAO/loot-survivor/issues/91)

This is going to make Charisma incredibly tempting in the early game but this will come at the cost of making your adventurer highly vulnerable to obstacles and beasts.

**Comment by loothero** [comment]
@Calcutatator we have tiered the minimum bid for the items based on the item tier. The commit for this is here <https://github.com/BibliothecaDAO/realms-contracts/commits?author=ponderingdemocritus>

I'm not sure I fully understand the decay function. So we can harvest our issues for release docs, I'm going to make this ticket specifically for the tiered. Can you repackage that suggestion in a separate issue?
