### ISSUE TITLE
Beast collection gameplay system

### ISSUE THREAD

**Issue by LordSecretive** [BibliothecaDAO/loot-survivor#4]
A method to:
1. track which beasts an Adventurer has encountered and slayed i.e. trophies
2. include the slayed beasts as trophies in an interface which displays all beasts that exists in the world ('beastdex' or similar)
3. show a leaderboard of which Adventurers have collected most trophies
4. 'share my beastdex and leaderboard position' to twitter function

Extensions:
5. potentially include beast rarity in the game e.g. some rare beasts only encountered after level 10
6. potential for traits like luck to influence possibility of encountering rare beasts
7. potential for leaderboard to create a beastdex score where the rank is based not only on percentage of beast trophies collected (e.g. 24 out of 48) but the rarity of the beasts in the beastdex.

Objective - to create an alternative goal in the game for players who want to collect / compete for the best collection

**Comment by starknetdev** [comment]
I don't think we will implement for the V1 as more work to get this implemented, currently prioritising making the current game smooth. Some notes for V2:

- For the beastdex it is relatively simple to add a tab that displays the beasts that you have slain. Currently there isn't rarity build in for these beasts, so really this will just be a cosmetic addition rather than an added feature to the game, and this rarity would require contract upgrades. If we then want to architect luck to also affect this rarity then that's also extra work to upgrade.

- Calculating the trophy system is cool, but also something that we should focus on once rarity has been added in V2 (we would add rarity not only for beasts but items, obstacles etc)
