### ISSUE TITLE
Game client does not pick up pending transactions after refresh

### ISSUE THREAD

**Issue by zomglings** [BibliothecaDAO/loot-survivor#67]
I accidentally refreshed the game site after going `Into the mist`. After I refreshed, I entered the game again with the same character (at this point my only character).

It did not show me my pending transaction so I tried clicking `Into the Mist` again. This resulted in `Transaction failure predicted` in my Argent X wallet.

After 2 more refreshes, I was confronted with an ogre (presumably from my mist exploration).

**Comment by loothero** [comment]
Hi @zomglings thanks for the report. This was likely due to our frontend/indexer being overwhelmed. We made a number of optimizations on the current version and upgraded our server infrastructure to a system with 10-20x more compute power

I'm going to optimistically close this issue, feel free to reopen though if you continue to see this behavior moving forward
