### ISSUE TITLE
Rewards for top leaders should be higher

### ISSUE THREAD

**Issue by GrugLikesRocks** [BibliothecaDAO/loot-survivor#84]
Currently (assuming 50 LORDS per survivor)
1st: 20% of cost
2nd: 6% of cost 
3rd: 2% of cost

I'd propose:
1st: 30% of cost
2nd: 14% of cost
3rd: 6% of cost

**Comment by loothero** [comment]
What do you think the reward should be for the front end provider (web app)? I think it should be equal to the player reward but if we do that, there are no tokens left for the DAO

What about 33% players, 33% frontend, 33% DAO?

Don't underestimate the frontend developers. It's not just about decentralizing the front-end for durability and creating the most immersive gameplay for a set of contracts, it's providing an incentive for shadowy super coders to share their advanced tooling instead of hoarding them and using them to pwn the normies.

If top score reward is OP, the shadowy super coders will be incentivized to keep their tools to themselves
