### ISSUE TITLE
Beast and level up simultaneously

### ISSUE THREAD

**Issue by Calcutatator** [BibliothecaDAO/loot-survivor#99]
Into the mist'd and got a level up and found a beast in the same trx. 

Upgrade popped up first and then got locked into the beast fight. Technically worked well but the flow felt a bit disconnected imo, as if a beast just glitched onto the screen.

trx -
https://testnet.starkscan.co/tx/0x326623c0135a1105f020362f258ab17fb333655c884f4362c4f27f2f9817ea8#events

Not sure the best fix to make it flow nicer, probably UI could make it clearer you found a best AND leveled up.

**Comment by loothero** [comment]
This was likely due to frontend/indexer lag. Contract doesn't grant XP until after you defeat a beast.

Did you defeat a beast or otherwise gain XP shortly before going exploring again? We're significantly improving the performance of the frontend tomorrow so if this was indeed frontend/indexer lag, it should be fixed moving forward

**Comment by Calcutatator** [comment]
I did think I only had that trx queued but I mustn't of been paying attention. Will keep an eye out see if it happens again.
